spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #spring.jpa.hibernate.ddl-auto: create 실행시점에서 테이블을 드랍하고 다시 실행
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace